### DISCUSSION TITLE
How to change latexindent options?

### DISCUSSION THREAD

**Discussion by oiiiiiiii** [James-Yu/LaTeX-Workshop#3483] [Q&A] [answered]
I want to configure latexindent.pl to format not only \item and \myitem within an itemize envrionment but also e.g. \item[-]. Therefore I adjusted my .identconfig.yaml in my home directory accordingly to load a settings.yaml like this:
```
itemNames:
    item: 1
    myitem: 1
    mitem: 1
    item[-]: 1
```
But when I use the formatter of LaTeX-Workshop, it doesn't work. When i use the command line to call latexindent it does work. I couldn't figure out why. Can anyone tell me how to set this up properly? Maybe also other latexindent options?
