### ISSUE TITLE
Configure background color of pdf viewer

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#304]
It will be great if we can customize the background color of the pdf viewer. Personally, I want it to be white because when updating the page, less brightness change and less distracting.

A hack of the css file in the extension shows the desired effect:

![xx](https://user-images.githubusercontent.com/9464825/32771152-c9e610d0-c95c-11e7-903a-ddc79deef1ca.PNG)

The hack is changing the `viewer/viewer.css`
```css
.pdfViewer.removePageBorders .page {
  margin: 0px auto 10px auto;
  border: 1px dashed lightgray; /* <-- change this line */
}

body {
  height: 100%;
  width: 100%;
  background-color: white; /* <-- also change this line, and delete the next background-image line */
}
```
