### ISSUE TITLE
Hide toolbar in pdf viewer

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#305]
It feels clean and good without the toolbar. A configuration to hide it would be great.

A hack is to change the `viewer/viewer.css`
```css
#toolbarContainer, .findbar, .secondaryToolbar {
  display: none; /* <-- add this line */
  position: relative;
  height: 32px;
  background-color: #474747; /* fallback */
  background-image: url(images/texture.png),
                    linear-gradient(hsla(0,0%,32%,.99), hsla(0,0%,27%,.95));
}

#viewerContainer {
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  position: absolute;
  top: 0; /* <-- and change this line */
  right: 0;
  bottom: 0;
  left: 0;
  outline: none;
}
```
